### ISSUE TITLE
not support python3

### ISSUE THREAD

**Issue by THAVASIGTI** [msteinhoff/vmfusion-python#10]
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vmfusion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/vmfusion/__init__.py", line 255
    except AttributeError, e:
                         ^
SyntaxError: invalid syntax
>>>

**Comment by msteinhoff** [comment]
I don't use VMware Fusion anymore.

Want to send a PR?
